language: python
python:
  - "2.7"
  - "3.6"
  - "3.8"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - python -m unittest tests.unit.test_degrotesque
  