site_name: degrotesque
site_url: https://github.com/dkrajzew/degrotesque
site_description: A web type setter
site_author: Daniel Krajzewicz
docs_dir: ./docs

repo_url: https://github.com/dkrajzew/degrotesque.git
edit_uri: ""

theme:
    name: material
    custom_dir: ./docs/materials_ext
    font: false
    palette:
        primary: green
        
extra_css:
    - stylesheets/extra.css
    - stylesheets/prism.css

extra_javascript:
    - js/prism.js

nav:
    - Home: index.md
    - Installation: install.md
    - Usage: 
        - Command Line: cmd.md
        - Embedded: embed.md
        - Use Cases: use_cases.md
    - Links: links.md
    - API:
        - degrotesque: api_degrotesque.md
        - marker API: api_marker.md
        - Abstract beg/end marker: api_marker_begend.md
        - HTML marker: api_marker_html.md
        - Markdown marker: api_marker_md.md
        - RST marker: api_marker_rst.md
        - Text marker: api_marker_text.md
        - Helper: api_helper.md
    - Developer Docs:
        - Workflow: workflow.md
        - How To Extend: extend.md
        - How To Release: release.md
        - Notes: notes.md
    - ChangeLog: changes.md
    - License (BSD): license.md
    - Legal: legal.md
    - Appendices:
        - Appendix A: appendixA.md
        - Appendix B: appendixB.md
        - Appendix C: appendixC.md
        - Appendix D: appendixD.md
    - Known Issues: issues.md
    - FAQ: faq.md
    - Services: services.md

exclude_docs:

markdown_extensions:
    - admonition
    - sane_lists
  
copyright: "&copy; Copyright 2020&ndash;2024 Daniel Krajzewicz."

use_directory_urls: false

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [./]
                options:
                    filters: [""]
                    show_source: False
                    docstring_style: "google"