site_name: degrotesque
site_url: https://github.com/dkrajzew/degrotesque
site_description: A web type setter
site_author: Daniel Krajzewicz
docs_dir: ./mkdocs

repo_url: https://github.com/dkrajzew/degrotesque.git
edit_uri: ""

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
    palette:
        primary: light green
        
nav:
    - Home: index.md
    - Installation: install.md
    - Usage: 
        - Command Line: cmd.md
        - Embedded: embed.md
    - ChangeLog: changes.md
    - Legal: legal.md
    - License (BSD): https://github.com/dkrajzew/degrotesque/blob/master/LICENSE
    - Links: links.md
    - Appendices:
        - AppendixA: appendixA.md
        - AppendixB: appendixB.md
        - AppendixC: appendixC.md
        - AppendixD: appendixD.md
    - Developer Docs:
        - Notes: notes.md
        - How To Release: release.md
    - API: api.md

markdown_extensions:
    - admonition
    - sane_lists
  
copyright: "&copy; Copyright 2020-2023 Daniel Krajzewicz."

use_directory_urls: false

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [..]
                options:
                    filters: [""]
                    show_source: False
                    docstring_style: "google"